# Generated by Django 3.1.5 on 2021-01-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deserts',
            options={'verbose_name': 'десерт', 'verbose_name_plural': 'десерты'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'ингредиент', 'verbose_name_plural': 'ингредиенты'},
        ),
        migrations.AlterField(
            model_name='deserts',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='main.Ingredient'),
        ),
    ]
