# Generated by Django 3.1.5 on 2021-01-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Напиток')),
                ('description', models.TextField(blank=True, verbose_name='Описание напитка')),
            ],
            options={
                'verbose_name': 'напиток',
                'verbose_name_plural': 'напитки',
            },
        ),
        migrations.RenameField(
            model_name='order',
            old_name='choices',
            new_name='food_choices',
        ),
        migrations.RemoveField(
            model_name='deserts',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.CharField(blank=True, max_length=50, verbose_name='Клиент'),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.AddField(
            model_name='order',
            name='drink_choices',
            field=models.ManyToManyField(to='main.Drinks'),
        ),
    ]
